// autogenerated

/**

@typedef Msg
 @property {string} _mt

@typedef SomeMsg
 @property {string} p
 @property {string[]} props
 @property {string} _mt

*/


export {};  // we just use this is a module for type checking
